### ISSUE TITLE
Tags not coloured

### ISSUE THREAD

**Issue by dummifiedme** [DubininDmitry/Obuntu#1]
The tags are not showing up coloured, every tag is orange.
Also, what is the way to remove the dissappearing of ###s?

**Comment by dmytrodubinin** [comment]
1. Orange is the default color for all tags. Changed colors set only for tags `#important`, `#complete` and `#inprogress`.
The rules can be automatically implemented within the plugin when the developers open the api. But at the moment, custom values must be registered manually in obsidian.css
Current styles:
```css
/* === Tag Pills === */

.tag {
  background-color: var(--text-accent);
  border: none;
  color: white !important;
  font-size: 11px;
  font-weight: bold;
  line-height: 1.6em;
  padding: 0px 7px 1px 7px;
  text-align: center;
  text-decoration: none !important;
  display: inline-block;
  margin: 0px 2px;
  cursor: pointer;
  border-radius: 10px;
}

.tag[href^="#important"] {
  background-color: red;
}

.tag[href^="#complete"] {
  background-color: green;
}

.tag[href^="#inprogress"] {
  background-color: orange;
}

.tag:hover {
  color: white;
  background-color: var(--text-accent-hover);
}
```

2. To remove the dissappearing of ###s you need to add this to exceptions. Find line `/* except list markers, links, images, urls and code blocks */` and add header tag `span.cm-header`
All code:
```css
span.cm-header,
span.cm-image,
span.cm-link,
span.cm-url,
span.cm-formatting-list,
span.cm-formatting-code-block.cm-hmd-codeblock {
  display: inline !important;
}
```
You can also disable all disappearing tags in edit mode. Just remove the code
```css
/* === Clutter free edit mode === */
/* inline formatting, link targets and [[ ]] disappears if not active line*/
div:not(.CodeMirror-activeline) > .CodeMirror-line span.cm-formatting {
  display: none;
}
/* except list markers, links, images, urls and code blocks */
span.cm-image,
span.cm-link,
span.cm-url,
span.cm-formatting-list,
span.cm-formatting-code-block.cm-hmd-codeblock {
  /* header hashes -  span.cm-formatting-header */
  display: inline !important;
}

/* hide all html tags -- IT IS COMMENTED OUT BY DEFAULT */
/* div:not(.CodeMirror-activeline) > .CodeMirror-line span.cm-tag{ display: none; } */

/* and task checkboxes */
span.cm-formatting-task {
  display: inline !important;
  font-family: monospace;
}

```
